version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]  # Adicionei -d airflow
      interval: 5s  # Reduzi para 5s
      timeout: 5s
      retries: 10   # Aumentei tentativas

  airflow:
    build: .
    container_name: airflow-standalone
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    ports:
      - "8081:8080"
    volumes:
      - ./airflow_home/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./airflow_home:/opt/airflow
      - ./src:/app/src
      - ./data:/app/data
    command: >
      bash -c "
      while ! pg_isready -h postgres -U airflow -d airflow -q; do
        echo 'Aguardando PostgreSQL...'
        sleep 5
      done &&
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow standalone
      "

volumes:
  postgres-db-volume: