version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  etl-container:
    build: .
    container_name: etl-container
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    ports:
      - "8081:8080"
      - "8888:8888"
    volumes:
      # DAGs das pipelines
      - ./airflow_home/dags:/opt/airflow/dags

            # Scripts utilitários chamados pelas DAGs
      - ./src:/app/src
      
      # Logs do Airflow
      - ./logs:/opt/airflow/logs
      
      # Configurações do Airflow
      - ./airflow_home:/opt/airflow

      - ./data:/app/data

    command: bash -c "airflow db init && airflow webserver"

volumes:
  postgres-db-volume:
